config/routes.rb
Rails.application.routes.draw do

  resources :restaurants, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:new, :create]
  end

  root 'restaurants#index'
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates_inclusion_of :category, in: %w( chinese italian japanese french belgian )
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :restaurant
  validates :restaurant_id, presence: true
  validates :content, presence: true
  validates :rating, numericality: { only_integer: true }, inclusion: { in: 0..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show]

  def index
    @restaurants = Restaurant.all
  end

  def show
    @review = Review.new
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private
  def set_restaurant
    id = params[:restaurant_id] || params[:id]
    @restaurant = Restaurant.find(id)
  end
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: [:index, :new, :create]

  def new
    @review = Review.new
  end

  def create
    @review = @restaurant.reviews.create(review_params)
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render 'restaurants/show'
      # render :new
    end
  end

  private
  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lacuillere</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "shared/navbar" %>
<%= yield %>

</body>
</html>

app/views/restaurants/index.html.erb
<div class="container">
  <div class="row">
    <% @restaurants.reverse.each do |restaurant| %>

      <% if restaurant.reviews.any? %>
        <% array = restaurant.reviews.map(&:rating).compact %>
        <% rating = array.inject(:+) / array.size %>
      <% end %>

      <div class="col-lg-4">
        <div class="card">
          <%= link_to restaurant_path(restaurant) do %>
            <h2><%= restaurant.name %></h2>
          <% end %>
          <p><%= restaurant.category.upcase %> - <%= ("<i class='fa fa-star' style='color: #FFCE54;'></i>" * rating.to_i).html_safe %></p>
          <p><%= restaurant.phone_number %></p>
          <p><%= restaurant.address %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="container">
    <div class="row">
      <div class="col-lg-6 col-lg-offset-3">
        <div class="card">
          <div class="text-center">
            <h3>Tell us about the restauant</h3>
          </div>
          <div>
            <%= simple_form_for(@restaurant) do |f| %>
              <%= f.error_notification %>

              <%= f.input :name %>
              <%= f.input :address %>
              <%= f.input :phone_number %>
              <%= f.input :category, collection: %w( chinese italian japanese french belgian ) %>

              <%= f.button :submit, class: 'btn btn-primary' %>
            <% end %>
          </div>
        </div>
      </div>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <div class="row text-center">
    <div class="col-lg-6 col-lg-offset-3">
      <div class="card">
        <% if @restaurant.reviews.any? %>
          <% rating = 0 %>
          <% array = @restaurant.reviews.map(&:rating).compact %>
          <% rating = array.inject(:+) / array.size %>
        <% end %>
        <h1><%= @restaurant.name %></h1>
        <p><%= @restaurant.category.upcase %> - <%= ("<i class='fa fa-star' style='color: #FFCE54;'></i>" * rating).html_safe %></p>
        <p><%= @restaurant.phone_number %></p>
        <p><%= @restaurant.address %></p>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-6 col-lg-offset-3">
      <div class="card">
        <div class="text-center">
          <h2>Reviews</h2>
          <h2><%= link_to ("<i class='fa fa-plus-square-o'></i>").html_safe, '#new-review' %></h2>
        </div>

        <% if @restaurant.reviews.any? %>
          <% @restaurant.reviews.each do |review| %>
            <% rating = review.rating.nil? ? 0 : review.rating %>
            <p><%= ("<i class='fa fa-star' style='color: #FFCE54;'></i>" * rating).html_safe %> - <%= review.content %></p>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row" id="new-review">
    <div class="col-lg-6 col-lg-offset-3">
      <div class="card">
        <%= render "reviews/new" %>
      </div>
    </div>
  </div>
</div>

app/views/reviews/_new.html.erb
<div class="text-center">
  <h3>Add your review</h3>
</div>
<div>
  <%= simple_form_for([@restaurant, @review]) do |f| %>
    <%= f.error_notification %>

    <%= f.input :content, label: "Your comment" %>
    <%= f.input :rating, collection: 0..5 %>

    <%= f.button :submit, class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <div class="row text-center">
    <div class="col-lg-6 col-lg-offset-3">
      <div class="card">
        <div class="text-center">
          <h3>Add your review</h3>
          <p><%= link_to "Go back", restaurant_path(@restaurant) %></p>
        </div>
        <div>
          <%= simple_form_for([@restaurant, @review]) do |f| %>
            <%= f.error_notification %>

            <%= f.input :content, label: "Your comment" %>
            <%= f.input :rating, collection: 0..5 %>

            <%= f.button :submit, class: 'btn btn-primary' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar-wagon">
  <div class="container navbar-wagon-container">

    <a href="/">
      <%= image_tag "logo_cuillere.png", id: "logo" %>
    </a>


    <div class="navbar-wagon-pusher"></div>
    <%= link_to "Add a restaurant", new_restaurant_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>
</nav>